version: '3.9'
networks:
  carshop:
    driver: bridge
services:
  backend:
    build: ./app/backend
    working_dir: /app/backend
    ports:
      - 3001:3001
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "lsof", "-t", "-i:3001"]
      timeout: 10s
      retries: 5
    links:
      - db
    networks:
      - carshop
  db:
    image: mongo:5.0
    container_name: db
    ports:
      - 27018:27018
    volumes:  
      - './data:/data/db'
    restart: 'always'
    environment:
      - MONGO_INITDB_DATABASE=carShop
    healthcheck:
      test: ["CMD","mongo", "--eval", "db.adminCommand('ping')"] 
      timeout: 10s
      retries: 5
    networks:
      - carshop
