version: '3.9'
services:
  backend:
    build: ./app/backend
    ports:
      - 3001:3001
    depends_on:
      db:
        condition: service_healthy
    environment:
      - PORT=3001
      - DB_USER=root
      - DB_PASS=123456
      - DB_HOST=db
      - DB_NAME=CRUD-CAR-SHOP-DOCKER
      - DB_PORT=27017
    healthcheck:
      test: ["CMD", "lsof", "-t", "-i:3001"]
      timeout: 10s
      retries: 5
  db:
    image: mongo:5.0
    container_name: db
    ports:
      - 27017:27017
    environment:
      - MONGO_ROOT_PASSWORD=123456
    restart: 'always'
    healthcheck:
      test: ["CMD","mongo", "--eval", "db.adminCommand('ping')"] 
      timeout: 10s
      retries: 5
    cap_add:
      - SYS_NICE
